# Generated by Django 3.0.7 on 2020-06-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_question_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='type',
            field=models.CharField(choices=[('m', 'Movíl'), ('w', 'Web')], max_length=50, verbose_name='Tipo'),
        ),
    ]
